---
title: "Cherry Bloom Predictions"
author: "Cole Boller-Pinkham"
date: "2026-02-28"
output: html_document
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, 
                      message = FALSE,
                      fig.align = 'center',
                      out.width = '80%')
```

```{r}
library(tidyverse)
```

```{r}
cherry <- read.csv("data/washingtondc.csv") |> 
  bind_rows(read.csv("data/liestal.csv")) |> 
  bind_rows(read.csv("data/kyoto.csv")) |> 
  bind_rows(read.csv("data/vancouver.csv")) |> 
  bind_rows(read.csv("data/nyc.csv"))
```

```{r}
#| fig-width: 8
#| fig-height: 3
#| out-width: 100%
#| fig-cap: |
#|   Time series of peak bloom of cherry trees since 1880 at four different sites.
cherry |> 
  filter(year >= 1880) |>
  ggplot(aes(x = year, y = bloom_doy)) +
  geom_point() +
  geom_step(linetype = 'dotted', color = 'gray50') +
  scale_x_continuous(breaks = seq(1880, 2020, by = 20)) +
  facet_grid(cols = vars(str_to_title(location))) +
  labs(x = "Year", y = "Peak bloom (days since Jan 1st)")
```

```{r}
DC <- read_csv("/Users/coleb-p/Desktop/College/STAT490/BloomData/USW00013743.csv.gz")
Van <- read_csv("/Users/coleb-p/Desktop/College/STAT490/BloomData/CA001108395.csv.gz")
NYC <- read_csv("/Users/coleb-p/Desktop/College/STAT490/BloomData/USW00014732.csv.gz")
Lei <- read_csv("/Users/coleb-p/Desktop/College/STAT490/BloomData/SZ000001940.csv.gz")
Kyo <- read_csv("/Users/coleb-p/Desktop/College/STAT490/BloomData/JA000047759.csv.gz")
```

```{r}
old_names <- colnames(DC)
DC <- rbind(old_names, DC)
colnames(DC) <- c("ID", "Date", "Element", "Temp", "M", "Q", "S", "OBS")

old_names <- colnames(Van)
Van <- rbind(old_names, Van)
colnames(Van) <- c("ID", "Date", "Element", "Temp", "M", "Q", "S", "OBS")

old_names <- colnames(NYC)
NYC <- rbind(old_names, NYC)
colnames(NYC) <- c("ID", "Date", "Element", "Temp", "M", "Q", "S", "OBS")

old_names <- colnames(Lei)
Lei <- rbind(old_names, Lei)
colnames(Lei) <- c("ID", "Date", "Element", "Temp", "M", "Q", "S", "OBS")

old_names <- colnames(Kyo)
Kyo <- rbind(old_names, Kyo)
colnames(Kyo) <- c("ID", "Date", "Element", "Temp", "M", "Q", "S", "OBS")
```

```{r}
DCtemp <- subset(DC, Element == "TMAX")
Vantemp <- subset(Van, Element == "TMAX")
Kyotemp <- subset(Kyo, Element == "TMAX")
Leitemp <- subset(Lei, Element == "TMAX")
NYCtemp <- subset(NYC, Element == "TMAX")
```

```{r}
library(dplyr)

DCtemp$Date <- as.character(DCtemp$Date)
Vantemp$Date <- as.character(Vantemp$Date)
Kyotemp$Date <- as.character(Kyotemp$Date)
Leitemp$Date <- as.character(Leitemp$Date)
NYCtemp$Date <- as.character(NYCtemp$Date)

DCtemp <- DCtemp %>%
  mutate(
    year = substr(Date, 1, 4),
    month_day = substr(Date, 5, 8)
  )

Vantemp <- Vantemp %>%
  mutate(
    year = substr(Date, 1, 4),
    month_day = substr(Date, 5, 8)
  )

Kyotemp <- Kyotemp %>%
  mutate(
    year = substr(Date, 1, 4),
    month_day = substr(Date, 5, 8)
  )

Leitemp <- Leitemp %>%
  mutate(
    year = substr(Date, 1, 4),
    month_day = substr(Date, 5, 8)
  )

NYCtemp <- NYCtemp %>%
  mutate(
    year = substr(Date, 1, 4),
    month_day = substr(Date, 5, 8)
  )

DCtemp$year <- as.numeric(DCtemp$year)
Vantemp$year <- as.numeric(Vantemp$year)
Kyotemp$year <- as.numeric(Kyotemp$year)
Leitemp$year <- as.numeric(Leitemp$year)
NYCtemp$year <- as.numeric(NYCtemp$year)

DCtemp$month_day <- as.numeric(DCtemp$month_day)
Vantemp$month_day <- as.numeric(Vantemp$month_day)
Kyotemp$month_day <- as.numeric(Kyotemp$month_day)
Leitemp$month_day <- as.numeric(Leitemp$month_day)
NYCtemp$month_day <- as.numeric(NYCtemp$month_day)

DCtemp$Temp <- as.numeric(DCtemp$Temp)
Vantemp$Temp <- as.numeric(Vantemp$Temp)
Kyotemp$Temp <- as.numeric(Kyotemp$Temp)
Leitemp$Temp <- as.numeric(Leitemp$Temp)
NYCtemp$Temp <- as.numeric(NYCtemp$Temp)
```

```{r}
library("tidyverse")
library("rvest")

get_weather_table <- function(url)
  read_html(url) %>% 
  html_nodes("div.monthly-calendar") %>% 
  html_text2() %>%
  str_replace("N/A", "N/A N/A") %>%
  str_remove_all("°|Hist. Avg. ") %>%
  str_split(" ", simplify = TRUE) %>%
  parse_number() %>%
  matrix(ncol = 3, 
         byrow = TRUE,
         dimnames = list(NULL, c("day", "tmax", "tmin"))) %>%
  as_tibble() %>%
  filter(row_number() >= day) %>%
  filter(!duplicated(day))

kyoto <-
  tibble(
    base_url = "https://web.archive.org/web/20260224/https://www.accuweather.com/en/jp/arashiyama/2334469/",
    month = month.name[1:3],
    year = 2026,
    url = str_c(base_url, tolower(month), "-weather/2334469?year=", year)) %>%
  mutate(temp = map(url, get_weather_table)) %>%
  pull(temp) %>%
  reduce(bind_rows) %>%
  transmute(date = seq(as.Date("2026-01-01"), as.Date("2026-03-31"), 1),
            year = parse_number(format(date, "%Y")),
            tmax = ifelse(is.na(tmax), (lag(tmax) + lead(tmax)) / 2, tmax),
            tmin = ifelse(is.na(tmin), (lag(tmin) + lead(tmin)) / 2, tmin),
            temp = (tmax + tmin) / 2)

liestal <-
  tibble(
    base_url = "https://web.archive.org/web/20260224/https://www.accuweather.com/en/ch/liestal/311994/",
    month = month.name[1:3],
    year = 2026,
    url = str_c(base_url, tolower(month), "-weather/311994?year=", year)) %>%
  mutate(temp = map(url, get_weather_table)) %>%
  pull(temp) %>%
  reduce(bind_rows) %>%
  transmute(date = seq(as.Date("2026-01-01"), as.Date("2026-03-31"), 1),
            year = parse_number(format(date, "%Y")),
            tmax,
            tmin,
            temp = (tmax + tmin) / 2)

newyork <-
  tibble(
    base_url = "https://web.archive.org/web/20260224/https://www.accuweather.com/en/us/new-york/10021/",
    month = month.name[1:3],
    year = 2026,
    url = str_c(base_url, tolower(month), "-weather/349727?year=", year)) %>%
  mutate(temp = map(url, get_weather_table)) %>%
  pull(temp) %>%
  reduce(bind_rows) %>%
  transmute(date = seq(as.Date("2026-01-01"), as.Date("2026-03-31"), 1),
            year = parse_number(format(date, "%Y")),
            tmax,
            tmin,
            temp = (tmax + tmin) / 2)

washington <-
  tibble(
    base_url = "https://web.archive.org/web/20260224/https://www.accuweather.com/en/us/washington/20006/",
    month = month.name[1:3],
    year = 2026,
    url = str_c(base_url, tolower(month), "-weather/18-327659_1_al?year=", year)) %>%
  mutate(temp = map(url, get_weather_table)) %>%
  pull(temp) %>%
  reduce(bind_rows) %>%
  transmute(date = seq(as.Date("2026-01-01"), as.Date("2026-03-31"), 1),
            year = parse_number(format(date, "%Y")),
            tmax,
            tmin,
            temp = (tmax + tmin) / 2)  

vancouver <-
  tibble(
    base_url = "https://web.archive.org/web/20260224/https://www.accuweather.com/en/us/vancouver/98661/",
    month = month.name[1:3],
    year = 2026,
    url = str_c(base_url, tolower(month), "-weather/331419?year=", year)) %>%
  mutate(temp = map(url, get_weather_table)) %>%
  pull(temp) %>%
  reduce(bind_rows) %>%
  transmute(date = seq(as.Date("2026-01-01"), as.Date("2026-03-31"), 1),
            year = parse_number(format(date, "%Y")),
            tmax,
            tmin,
            temp = (tmax + tmin) / 2)
```

```{r}
library(dplyr)

kyoto <- kyoto %>%
  mutate(
    month_day = format(date, "%m%d")
  )

vancouver <- vancouver %>%
  mutate(
    month_day = format(date, "%m%d")
  )

liestal <- liestal %>%
  mutate(
    month_day = format(date, "%m%d")
  )

newyork <- newyork %>%
  mutate(
    month_day = format(date, "%m%d")
  )

washington <- washington %>%
  mutate(
    month_day = format(date, "%m%d")
  )

kyoto$month_day <- as.numeric(kyoto$month_day)
vancouver$month_day <- as.numeric(vancouver$month_day)
liestal$month_day <- as.numeric(liestal$month_day)
washington$month_day <- as.numeric(washington$month_day)
newyork$month_day <- as.numeric(newyork$month_day)

kyoto$tmax <- round((kyoto$tmax - 32) * 5/9, 3)
vancouver$tmax <- round((vancouver$tmax - 32) * 5/9, 3)
liestal$tmax <- round((liestal$tmax - 32) * 5/9, 3)
washington$tmax <- round((washington$tmax - 32) * 5/9, 3)
newyork$tmax <- round((newyork$tmax - 32) * 5/9, 3)
```

```{r}
kyoto$tmax <- kyoto$tmax * 10
vancouver$tmax <- vancouver$tmax * 10
liestal$tmax <- liestal$tmax * 10
washington$tmax <- washington$tmax * 10
newyork$tmax <- newyork$tmax * 10
```

```{r}
kyoto$tmax <- round(kyoto$tmax, 0)
vancouver$tmax <- round(vancouver$tmax, 0)
liestal$tmax <- round(liestal$tmax, 0)
washington$tmax <- round(washington$tmax, 0)
newyork$tmax <- round(newyork$tmax, 0)
```

```{r}
library(dplyr)

ref_DC <- washington %>%
  filter(year == 2026) %>%
  select(month_day, Temp_2026 = tmax)

ref_Van <- vancouver %>%
  filter(year == 2026) %>%
  select(month_day, Temp_2026 = tmax)

ref_Kyo <- kyoto %>%
  filter(year == 2026) %>%
  select(month_day, Temp_2026 = tmax)

ref_Lei <- liestal %>%
  filter(year == 2026) %>%
  select(month_day, Temp_2026 = tmax)

ref_NYC <- newyork %>%
  filter(year == 2026) %>%
  select(month_day, Temp_2026 = tmax)
```

```{r}
washington$location <- "washingtondc"
kyoto$location <- "kyoto"
vancouver$location <- "vancouver"
liestal$location <- "liestal"
newyork$location <- "newyorkcity"

DCtemp$location <- "washingtondc"
Kyotemp$location <- "kyoto"
Vantemp$location <- "vancouver"
Leitemp$location <- "liestal"
NYCtemp$location <- "newyorkcity"
```

```{r}
library(dplyr)
temps <- bind_rows(DCtemp, Kyotemp, Leitemp, NYCtemp, Vantemp)
```

```{r}
comparisonDC <- temps %>%
  filter(year != 2026) %>%
  inner_join(ref_DC, by = "month_day") %>%
  group_by(location, year) %>%
  summarise(
    mean_diff = mean(abs(Temp - Temp_2026), na.rm = TRUE),
    matched_days = n()
  ) %>%
  ungroup() %>%
  filter(matched_days >= 0.9 * nrow(ref_DC)) %>%
  arrange(mean_diff)

top10DC <- comparisonDC %>%
  slice_head(n = 10)

DC_doy <- cherry %>%
  semi_join(top10DC, by = c("year", "location")) %>%
  summarise(mean_doy = round(mean(bloom_doy, na.rm = TRUE), 0))

top10DC
DC_doy
```

```{r}
comparisonKyo <- temps %>%
  filter(year != 2026) %>%
  inner_join(ref_Kyo, by = "month_day") %>%
  group_by(location, year) %>%
  summarise(
    mean_diff = mean(abs(Temp - Temp_2026), na.rm = TRUE),
    matched_days = n()
  ) %>%
  ungroup() %>%
  filter(matched_days >= 0.9 * nrow(ref_Kyo)) %>%
  arrange(mean_diff)

top10Kyo <- comparisonKyo %>%
  slice_head(n = 10)

Kyo_doy <- cherry %>%
  semi_join(top10Kyo, by = c("year", "location")) %>%
  summarise(mean_doy = round(mean(bloom_doy, na.rm = TRUE), 0))

top10Kyo
Kyo_doy
```

```{r}
comparisonLei <- temps %>%
  filter(year != 2026) %>%
  inner_join(ref_Lei, by = "month_day") %>%
  group_by(location, year) %>%
  summarise(
    mean_diff = mean(abs(Temp - Temp_2026), na.rm = TRUE),
    matched_days = n()
  ) %>%
  ungroup() %>%
  filter(matched_days >= 0.9 * nrow(ref_Lei)) %>%
  arrange(mean_diff)

top10Lei <- comparisonLei %>%
  slice_head(n = 10)

Lei_doy <- cherry %>%
  semi_join(top10Lei, by = c("year", "location")) %>%
  summarise(mean_doy = round(mean(bloom_doy, na.rm = TRUE), 0))

top10Lei
Lei_doy
```

```{r}
comparisonNYC <- temps %>%
  filter(year != 2026) %>%
  inner_join(ref_NYC, by = "month_day") %>%
  group_by(location, year) %>%
  summarise(
    mean_diff = mean(abs(Temp - Temp_2026), na.rm = TRUE),
    matched_days = n()
  ) %>%
  ungroup() %>%
  filter(matched_days >= 0.9 * nrow(ref_DC)) %>%
  arrange(mean_diff)

top10NYC <- comparisonNYC %>%
  slice_head(n = 10)

NYC_doy <- cherry %>%
  semi_join(top10NYC, by = c("year", "location")) %>%
  summarise(mean_doy = round(mean(bloom_doy, na.rm = TRUE), 0))

top10NYC
NYC_doy
```

```{r}
comparisonVan <- temps %>%
  filter(year != 2026) %>%
  inner_join(ref_Van, by = "month_day") %>%
  group_by(location, year) %>%
  summarise(
    mean_diff = mean(abs(Temp - Temp_2026), na.rm = TRUE),
    matched_days = n()
  ) %>%
  ungroup() %>%
  filter(matched_days >= 0.9 * nrow(ref_Van)) %>%
  arrange(mean_diff)

top10Van <- comparisonVan %>%
  slice_head(n = 10)

Van_doy <- cherry %>%
  semi_join(top10Van, by = c("year", "location")) %>%
  summarise(mean_doy = round(mean(bloom_doy, na.rm = TRUE), 0))

top10Van
Van_doy
```

```{r}
DCpred <- data.frame(location = "washingtondc", predicted_doy = as.numeric(DC_doy[1,1]))
Kyopred <- data.frame(location = "kyoto", predicted_doy = as.numeric(Kyo_doy[1,1]))
Leipred <- data.frame(location = "liestal", predicted_doy = as.numeric(Lei_doy[1,1]))
NYCpred <- data.frame(location = "newyorkcity", predicted_doy = as.numeric(NYC_doy[1,1]))
Vanpred <- data.frame(location = "vancouver", predicted_doy = as.numeric(Van_doy[1,1]))
predictions <- bind_rows(DCpred, Kyopred, Leipred, NYCpred, Vanpred)
predictions
```
